imart302/DevHuerta

- README.md
> [chore]:0000 Update README.md

- README.md
> Chore 00 test

- README.md
> sync main to dev

- README.md
* [chore]:0000 Update README.md
* test
---------
> Chore 00 test (#2) (#4)

- README.md
> Test ahead 1

- README.md
> Test ahead 2

- README.md
> chore-reset-readme

- README.md
> modify readme 1

- README.md
> Merge dev a main

- README.md
> modify test 1

- README.md
> modify 2 test

- README.md
> chore: should conflict 1

- LICENSE
- README.md
> Test merge dev to main

- LICENSE
- README.md
Merge to main test before merge conflicts
> Merge to main

- README.md
> Merge to main (#26)

- README.md
chore-test4-1 more commits test
> chore-test4-1

- LICENSE
- README.md
> PR dev to main

- contact.html
- js/contact.js
- styles/contact.css
- Se agrego la clase 'container' contenerdor principal
- se agregaron las clases 'btn btn-primary' al submit del form
-  se importaron correctamente los estilos root y del nabvar
- se hizo la validación de los inputs del form
> Arreglar estilos de la pagina de contacto y validar

- about-us.html
- contact.html
- index.html
- js/lib/minirender/weekProduct.js
- store.html
- styles/contact.css
- styles/index.css
- styles/root.css
> fix(DPI-27): Fix generales.

- .vscode/settings.json
- js/api/dtos/product.js
- js/api/products.js
- js/lib/minirender/productShopCard.js
- js/products.js
- js/store.js
- store.html
- styles/root.css
- styles/store.css
- Se crea la pagina de productos
- Se añade un template de tarjeta de compra de producto
- Se crea clase Dto para simular producto de la API
- Se modifican y añaden estilos correspondientes
- Se crea una clase render de ProductShopCard
- Se crea un script para llamadas a API de products
> feat(DPI-27): Pagina de productos

- js/index.js
- js/lib/minirender/reviewsCard.js
- js/review.js
- review.html
- styles/contact.css
- styles/review.css
-se creo pagina dereseñas
-se agrego validacion al formulario de agregar nueva reseña
-se creo una clase ReviewCard para renderizar una nueva reseña en la lista ya existente
-se ha creado una variable current User en el localStorage para un usuario que ha iniciado sesion
> DPI-26 Crear pagina de reseñas

- .vscode/settings.json
- about-us.html
- contact.html
- index.html
- js/contact.js
- js/index.js
- js/lib/minirender/newsCard.js
- js/lib/minirender/productShopCard.js
- js/lib/minirender/reviewsCard.js
- js/lib/minirender/weekProduct.js
- js/review.js
- js/store.js
- review.html
- store.html
- styles/about-us.css
- styles/contact.css
- styles/index.css
- styles/review.css
- styles/store.css
-Se corrigieron bugs relacionados a enlaces entre archivos y de gitpages
-se dio formato a todas las paginas
-se modifico archivo de ajustes de vscode
> DPI-29 (FIX) ajustes, correcciones y formato de paginas maquetadas

- about-us.html
- admin/js/management.js
- admin/management.html
- admin/styles/management.css
- auth/register.html
- js/about-us.js
- js/api/dtos/product.js
- js/api/products.js
- js/components/navbar.js
- js/contact.js
- js/lib/minirender/admin/productList.js
- js/review.js
- js/store.js
fix: Github pages js imports still not work, and formating
> fix: Github pages js imports still not work, and formating

- src/js/api/dtos/review.js
- src/js/api/reviews.js
- src/js/lib/minirender/reviewsCard.js
- src/js/review.js
-se creo una clase Review para a partir de la cual se crean las reseñas(fake)
-Se instanciaron reseñas a partir de Review, y se exportan por medio de una funcion getReviews()
-Se refactorizo la clase ReviewCard para que renderize el nuevo formato de reseñas.
> DPI-34 Cambiar la estructura en que se cargan las reseñas a la pagina de reseñas.

- src/index.html
- src/js/account.js
- src/js/auth/login.js
- src/js/review.js
- src/store.html
archivos modificados 
modified:   src/index.html
modified:   src/js/account.js
modified:   src/js/auth/login.js
modified:   src/js/review.js
modified:   src/store.html
> DPI(35) Redirecciones a login

- src/admin/js/management.js
- src/admin/management.html
Link a Jira Ticket https://decode-e-comerce.atlassian.net/browse/DPI-60, Se resuelven bugs de validación al crear y modificar items en la lista de productos
> Jira ticket DPI-60

- src/about-us.html
- src/review.html
- src/store.html
- src/styles/about-us.css
- src/styles/review.css
- src/styles/root.css
- src/styles/store.css
Fixes en banner de paginas:
>sobre nosotros
>tienda
>reseña
> Fix front-end

- src/cart.html
- src/js/cart.js
- src/js/lib/minirender/cartItem.js
- src/styles/cart.css
- src/styles/root.css
Se agrega más diseño al banner entre paginas
> fix(cart): tamaño botones de carrito

- src/admin/js/management.js
- src/js/api/dtos/product.js
- src/js/api/products.js
Se confirma el funcionamiento de la tienda y de la sección management, queda pendiente el manejo del token en la sección admin
> Integracion BE

- src/js/api/dtos/review.js
- src/js/api/reviews.js
- src/js/lib/minirender/reviewsCard.js
- src/js/review.js
- src/review.html
- src/styles/review.css
Se agrego el fetch a la API para:
> obtener todas las reseñas
> Crear reseña nueva
> Se refactorizo parte del codigo según fue necesario.
> Integración BE (GET, POST)

- src/admin/js/management.js
- src/js/api/dtos/product.js
- src/js/api/products.js
- src/js/components/navbar.js
- src/js/store.js
> ProductDbDto usage

- src/js/api/reviews.js
- src/js/lib/minirender/reviewsCard.js
- src/js/review.js
- src/styles/review.css
* se agrego funcionalidad para metodo DELETE
* revision final
---------
> integracion-BE (se agrego la función de eliminar reseña) (#104)
